### ISSUE TITLE
Fix responsiveness of vertically aligned hero image text

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#13]
![resp](https://cloud.githubusercontent.com/assets/539962/8948767/6e386e9c-355f-11e5-97f3-2aea6143b8ec.jpg)

Uh oh. find out what might be happening and what our options are to fix it code-wise. 

This may not be possible depending on what you find. 

due date:
7-28-15   11p

**Comment by purplyrocky** [comment]
I improved it by adding a min-height of 291px on each the <p> and the jumbotron image. that overlap is happening because the image is only 291px high so it doesn't resize larger when the same way as the <p>.  If i set the min-height lower, it could work, it will just crop the photo a bit and that photo is already short.
