### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#14]
![screen shot 2015-08-04 at 5 21 35 pm](https://cloud.githubusercontent.com/assets/539962/9075751/6b654528-3acd-11e5-94b9-1b4c03d7406f.png)

On the Services page. Please align it according to the other content. 

Attention to detail Aaron..  >:( 

;D

due:
8-4-15    9p

**Comment by rodneystrong** [comment]
![screen shot 2015-08-04 at 5 25 29 pm](https://cloud.githubusercontent.com/assets/539962/9075780/d90eec14-3acd-11e5-8402-2fcfc772b799.png)


Same with the staff page

**Comment by AaronAguilar** [comment]
Fixed when I aligned everything to look like the mock-up and added more pages.

**Comment by rodneystrong** [comment]
good stuff good stuff

could you do me a quick favor and comment here with a bullet point list of changes you had to make so i can double check them please? thanks!

**Comment by AaronAguilar** [comment]
I just went inside and did more styling to it. Rocky had a lot of the layout and content done, so it didn't take much! 

- Made a class row so that the content has a padding of about 15 px within the container. 
- Took off the offset col of 1 on the sidebar and left is to col-3 with a col-9 of the main content so that there's not a big gap between the content and sidebar. This gives more space to the content so that things don't have to look too squished in together (such as the icons on the home page). 
- Edited the fonts, Roboto Condensed was missing as well as Lato and Droid Serif. 
- Added content for some pages, for example, I added the content on the New Patients page
- Added an offset col on the footer so that's it has padding and is more centered.
